# This file is used by the pretix team internally to coordinate releases of this plugin
[plugin]
package = "pretix-fontpack-free"
modules = [ "pretix_fontpackfree" ]
marketplace_name = "fontpack-free"
pypi = true
repository_servers = { origin = "github.com", gitlab = "code.rami.io" }
tag_targets = [ "origin", "gitlab" ]
branch_targets = [ "origin/master", "gitlab/master", "f:gitlab/pypi" ]

